# Docker
trigger:
- main

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'
stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: Docker@2
      displayName: Build an image
      inputs:
        command: build
        dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
        tags: |
          $(tag)
    - task: ContainerBuild@0
      inputs:
        Dockerfile: 'Dockerfile'
    
    - task: Kubernetes@1
      inputs:
        connectionType: 'Kubernetes Service Connection'
        command: 'create'
        secretType: 'dockerRegistry'
        containerRegistryType: 'Azure Container Registry'
      
